# install_docker.yaml
---
- name: Install Docker CE
  hosts: "{{ survey_hostname | regex_replace('^(.*?)(\\.sarvent\\.net)?$', '\\1.sarvent.net') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - include_tasks: os/debian.yml
      when: ansible_os_family == "Debian"

    - include_tasks: os/redhat.yml
      when: ansible_os_family == "RedHat" || ansible_os_family == "Rocky" || ansible_os_family == "AlmaLinux"
